import { FuriganaOverlay } from './furigana';
import { FuriganaMessage } from './types';

const BUILTIN_DICT: Record<string, string> = {
  '私': 'わたし',
  '僕': 'ぼく',
  '俺': 'おれ',
  '彼': 'かれ',
  '彼女': 'かのじょ',
  '今日': 'きょう',
  '明日': 'あした',
  '昨日': 'きのう',
  '今': 'いま',
  '時間': 'じかん',
  '人': 'ひと',
  '人間': 'にんげん',
  '日本': 'にほん',
  '日本語': 'にほんご',
  '英語': 'えいご',
  '言葉': 'ことば',
  '学校': 'がっこう',
  '先生': 'せんせい',
  '生徒': 'せいと',
  '勉強': 'べんきょう',
  '友達': 'ともだち',
  '家族': 'かぞく',
  '父': 'ちち',
  '母': 'はは',
  '兄': 'あに',
  '姉': 'あね',
  '弟': 'おとうと',
  '妹': 'いもうと',
  '子供': 'こども',
  '大人': 'おとな',
  '男': 'おとこ',
  '女': 'おんな',
  '本': 'ほん',
  '机': 'つくえ',
  '椅子': 'いす',
  '車': 'くるま',
  '電車': 'でんしゃ',
  '飛行機': 'ひこうき',
  '駅': 'えき',
  '家': 'いえ',
  '部屋': 'へや',
  '台所': 'だいどころ',
  '風呂': 'ふろ',
  '便所': 'べんじょ',
  '玄関': 'げんかん',
  '水': 'みず',
  '湯': 'ゆ',
  '茶': 'ちゃ',
  '牛乳': 'ぎゅうにゅう',
  '食': 'しょく',
  '食事': 'しょくじ',
  '朝': 'あさ',
  '昼': 'ひる',
  '夜': 'よる',
  '夕方': 'ゆうがた',
  '春': 'はる',
  '夏': 'なつ',
  '秋': 'あき',
  '冬': 'ふゆ',
  '月': 'つき',
  '日': 'ひ',
  '年': 'とし',
  '週': 'しゅう',
  '時': 'じ',
  '分': 'ふん',
  '秒': 'びょう',
  '何': 'なに',
  '誰': 'だれ',
  '何処': 'どこ',
  '何時': 'いつ',
  '読': 'よ',
  '読書': 'どくしょ',
  '書': 'か',
  '聞': 'き',
  '話': 'はな',
  '会話': 'かいわ',
  '見': 'み',
  '行': 'い',
  '来': 'く',
  '帰': 'かえ',
  '食べ物': 'たべもの',
  '飲み物': 'のみもの',
  '魚': 'さかな',
  '肉': 'にく',
  '野菜': 'やさい',
  '果物': 'くだもの',
  '米': 'こめ',
  '麺': 'めん',
  '色': 'いろ',
  '赤': 'あか',
  '青': 'あお',
  '白': 'しろ',
  '黒': 'くろ',
  '黄色': 'きいろ',
  '緑': 'みどり',
  '大': 'だい',
  '小': 'しょう',
  '中': 'ちゅう',
  '上': 'うえ',
  '下': 'した',
  '左': 'ひだり',
  '右': 'みぎ',
  '前': 'まえ',
  '後': 'うし',
  '外': 'そと',
  '内': 'うち',
  '町': 'まち',
  '村': 'むら',
  '国': 'くに',
  '世界': 'せかい',
  '地球': 'ちきゅう',
  '空': 'そら',
  '海': 'うみ',
  '山': 'やま',
  '川': 'かわ',
  '森': 'もり',
  '木': 'き',
  '花': 'はな',
  '草': 'くさ',
  '雨': 'あめ',
  '雪': 'ゆき',
  '風': 'かぜ',
  '雲': 'くも',
  '太陽': 'たいよう',
  '星': 'ほし',
  '火': 'ひ',
  '土': 'つち',
  '金': 'きん',
  '銀': 'ぎん',
  '銅': 'どう',
  '鉄': 'てつ',
  '石': 'いし',
  '紙': 'かみ',
  '糸': 'いと',
  '布': 'ぬの',
  '服': 'ふく',
  '靴': 'くつ',
  '帽子': 'ぼうし',
  '眼鏡': 'めがね',
  '目': 'め',
  '耳': 'みみ',
  '鼻': 'はな',
  '口': 'くち',
  '手': 'て',
  '足': 'あし',
  '頭': 'あたま',
  '顔': 'かお',
  '体': 'からだ',
  '心': 'こころ',
  '気持': 'きも',
  '気持ち': 'きもち',
  '元気': 'げんき',
  '病気': 'びょうき',
  '医者': 'いしゃ',
  '看護師': 'かんごし',
  '薬': 'くすり',
  '病院': 'びょういん',
  '仕事': 'しごと',
  '会社': 'かいしゃ',
  '社員': 'しゃいん',
  '会議': 'かいぎ',
  '電話': 'でんわ',
  '電気': 'でんき',
  '機械': 'きかい',
  '道具': 'どうぐ',
  '物': 'もの',
  '事': 'こと',
  '所': 'ところ',
  '場所': 'ばしょ',
  '名前': 'なまえ',
  '住所': 'じゅうしょ',
  '番号': 'ばんごう',
  '一': 'いち',
  '二': 'に',
  '三': 'さん',
  '四': 'よん',
  '五': 'ご',
  '六': 'ろく',
  '七': 'なな',
  '八': 'はち',
  '九': 'きゅう',
  '十': 'じゅう',
  '百': 'ひゃく',
  '千': 'せん',
  '万': 'まん',
  '億': 'おく',
  '兆': 'ちょう',
  '円': 'えん',
  '値段': 'ねだん',
  '高': 'たか',
  '安': 'やす',
  '新': 'あたら',
  '古': 'ふる',
  '良': 'よ',
  '悪': 'わる',
  '美味': 'おい',
  '美味しい': 'おいしい',
  '楽': 'たの',
  '苦': 'くる',
  '難': 'むずか',
  '難読': 'なんどく',
  '簡単': 'かんたん',
  '読み上げ': 'よみあげ',
  '速度': 'そくど',
  '調整': 'ちょうせい',
  '機能': 'きのう',
  '設定': 'せってい',
  '保存': 'ほぞん',
  '削除': 'さくじょ',
  '追加': 'ついか',
  '更新': 'こうしん',
};

const dict = new Map<string, string>(Object.entries(BUILTIN_DICT));
const overlay = new FuriganaOverlay(dict);

function loadUserDict(): void {
  if (typeof chrome === 'undefined' || !chrome.storage?.local) return;
  chrome.storage.local.get(['furigana_dict'], (result) => {
    const userDict = result?.furigana_dict;
    if (userDict && typeof userDict === 'object') {
      const merged = new Map(dict);
      for (const [k, v] of Object.entries(userDict as Record<string, string>)) {
        if (typeof v === 'string') merged.set(k, v);
      }
      overlay.setDictionary(merged);
    }
  });
}

loadUserDict();

if (typeof chrome !== 'undefined' && chrome.runtime?.onMessage) {
  chrome.runtime.onMessage.addListener(
    (message: FuriganaMessage, _sender, sendResponse) => {
      switch (message.type) {
        case 'FURIGANA_ENABLE':
          overlay.enable(message.options);
          sendResponse({ success: true, state: overlay.getState() });
          return false;
        case 'FURIGANA_DISABLE':
          overlay.disable();
          sendResponse({ success: true, state: overlay.getState() });
          return false;
        case 'FURIGANA_TOGGLE':
          overlay.toggle(message.options);
          sendResponse({ success: true, state: overlay.getState() });
          return false;
        case 'GET_FURIGANA_STATE':
          sendResponse({ state: overlay.getState() });
          return false;
      }
      return false;
    }
  );
}

console.log('Content script initialized (furigana overlay ready).');
